#!/bin/bash

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


# ASCII art banner
BANNER="
  ${RED}····················································${NC}
  ${RED}:  ____                  ____           _ _        :${NC}
  ${RED}: |  _ \  ___  ___ _ __ |  _ \ __ _  __| (_) ___   :${NC}
  ${RED}: | | | |/ _ \/ _ \  _ \| |_) / _  |/ _  | |/ _ \  :${NC}
  ${RED}: | |_| |  __/  __/ |_) |  _ < (_| | (_| | | (_) | :${NC}
  ${RED}: |____/ \___|\___| .__/|_| \_\__,_|\__,_|_|\___/  :${NC}
  ${RED}:                 |_|                              :${NC}
  ${RED}: ${YELLOW}                          ~ by deepotrus${NC}         ${RED}:${NC}
  ${RED}····················································${NC}
"

# Define the radio menu options and corresponding commands
declare -A radio_menu
radio_menu["Ambient"]="ambient.ogg.m3u"
radio_menu["Trance"]="trance.ogg.m3u"
radio_menu["Tronic"]="tronic.ogg.m3u"
radio_menu["Dubstep"]="dubstepfm.ogg.m3u"

stations_dir="stations"

# Function to display the radio menu
display_menu() {
  clear
  echo -e "$BANNER"
  echo -e "  ${RED}~~~~ ${NC}${YELLOW}Radio Menu${NC}${RED} ~~~~${NC}"
  echo -e "  ${GREEN} 1. Trance${NC}"
  echo -e "  ${GREEN} 2. Ambient${NC}"
  echo -e "  ${GREEN} 3. Tronic${NC}"
  echo -e "  ${GREEN} 4. Dubstep${NC}"
  echo -e "  ${GREEN} 5. Quit${NC}"
  echo -e "  ${RED}~~~~~~~~~~~~~~~~~~~~${NC}"
}

play_radio_stream() {
  clear
  echo -e "$BANNER"
  echo "Playing $1" radio stream...
  mpv "${stations_dir}/${radio_menu[$1]}"
}

# Main program loop
while true; do
  display_menu
  read -p "Select an option: " option

  case $option in
  1 | 2 | 3 | 4)
    option_name=$(echo "${!radio_menu[@]}" | cut -d' ' -f$option)
    play_radio_stream "$option_name"
    ;;
  5)
    echo "Goodbye!"
    exit 0
    ;;
  *)
    echo "$BANNER"
    echo "Invalid option. Please try again."
    read -p "Press Enter to continue..."
    ;;
  esac
done
